# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:

  build:
    strategy:
      matrix:
        go-version: [ '1.20', '1.19', '1.18' ]
        os: [ 'ubuntu-latest' ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout mailtrap-go
        uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 3m

      - name: Test
        run: make cover

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
